# Configurations
title: Custom Firmware Tutorial
longtitle: Switch OpenCourse Custom Firmware Tutorial GitBook
author: jshsakura
email: jshsakura@gmail.com
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
description: >
  Build Jekyll site with the GitBook style.
user_verification: Hcve4yZ6k9qHCwxK_9bF2kYULoYHEGtf9f19mPXoSvQ
user_adsense_client: ca-pub-3553523371446563

version: 1.0
gitbook_version: 3.2.3

url: "https://jshsakura.github.io"
baseurl: "/gitbook"
rss: RSS
  
toc:
  enabled: true
  h_min: 1
  h_max: 3

comments:
  gitalk:
    clientID: af872a61510f2d69d14e
    clientSecret: 4153601d63c75fc018641d1cab52492f9dc71fd3
    repo: gitbook_comment
    owner: jshsakura
    admin: jshsakura

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "assets/**/*.*"
    values:
      sitemap: false